server:
  port: 9002
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
        - id: rpc
          uri: lb://RPC
          predicates:
            - Path=/rpc/**
          filters:
            - StripPrefix=1
        - id: sso
          uri: lb://SSO
          predicates:
            - Path=/sso/**
          filters:
            - StripPrefix=1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/